AWSTemplateFormatVersion: '2010-09-09'

Description: Create administrative IAM group and user

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      pAdminGroupName:
        default: Admin Group Name
      pAdminUserName:
        default: Admin User Name
      pAdminUserPassword:
        default: Admin User Password
        
Parameters:

  pAdminGroupName:
    Description: Administrator group name
    Type: String
    Default: 'Admins'

  pAdminUserName:
    Description: Administrator user name
    Type: String
    Default: 'Administrator'

  pAdminUserPassword:
    Type: String
    AllowedPattern: .* # Consider enhancing pattern per requirements. e.g. AllowedPattern: [a-zA-Z0-9]*
    ConstraintDescription: 'Must conform to password policy'
    Description: Admin user's initial password
    NoEcho: True

Resources:

  rAdminGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: !Ref pAdminGroupName
      ManagedPolicyArns:
         - arn:aws:iam::aws:policy/AdministratorAccess 

  rAdminUser:
    Type: "AWS::IAM::User"
    Properties: 
      Groups:
        - !Ref rAdminGroup
      LoginProfile:
        Password: !Ref pAdminUserPassword
        PasswordResetRequired: true
      UserName: !Ref pAdminUserName
