AWSTemplateFormatVersion: 2010-09-09
Description: Enable AWS CloudTrail. This template creates a CloudTrail trail, an Amazon S3 bucket where logs are published, and an Amazon SNS topic where notifications are sent.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Trail Configuration
        Parameters:
          - EnableLogFileValidation
          - IncludeGlobalEvents
          - MultiRegion
      - Label:
          default: Delivery Notifications
        Parameters:
          - PublishToTopic
          - SNSTopic
      - Label:
          default: Logging Bucket
        Parameters:
          - TrailBucket
    ParameterLabels:
      EnableLogFileValidation:
        default: Enable log file validation
      IncludeGlobalEvents:
        default: Include global service events
      MultiRegion:
        default: Is this a multi-region trail
      PublishToTopic:
        default: Send notifications to SNS
      SNSTopic:
        default: SNS Topic Name
      TrailBucket:
        default: Loggin Bucket Name

Parameters:
  EnableLogFileValidation:
    Type: String
    Default: 'True'
    Description: Indicates whether CloudTrail validates the integrity of log files.
    AllowedValues:
      - 'True'
      - 'False'

  IncludeGlobalEvents:
    Type: String
    Default: 'True'
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    AllowedValues:
      - 'True'
      - 'False'

  MultiRegion:
    Type: String
    Default: 'True'
    Description: Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all regions (true).
    AllowedValues:
      - 'True'
      - 'False'

  PublishToTopic:
    Type: String
    Default: 'False'
    Description: Indicates whether notifications are published to SNS.
    AllowedValues:
      - 'True'
      - 'False'

  SNSTopic:
    Type: String
    Default: ''
    Description: Topic for your notifications.

  TrailBucket:
    Type: String
    Default: ''
    Description: Bucket name for logs.

Conditions:
  IsMultiRegion: !Equals
    - !Ref MultiRegion
    - True

Resources:
  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref TrailBucket # update this
      SnsTopicName: !Ref SNSTopic
      IsLogging: true
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !If
        - IsMultiRegion
        - true
        - !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion
